services:
  - type: web
    name: ai-agent-marketing-crew
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8001
      - key: GROQ_API_KEY
        value: "gsk_..."
      - key: SERPER_API_KEY
        value: "c8ac..."
      - key: OPENAI_API_KEY
        value: "NA"
      - key: GEMINI_API_KEY
        value: "NA"
